// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
// app/(private)/layout.tsx
import Link from 'next/link';
import '../globals.css'; // Global styles
import Navbar from './components/navbar';

export const metadata = {
  title: 'Private Pages',
  description: 'Private area for authenticated users',
};

export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
